export enum EnvironmentEnum {
  NODE_ENV = 'NODE_ENV',
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_PORT = 'TYPEORM_PORT',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_SYNCHRONIZE = 'TYPEORM_SYNCHRONIZE',
  TYPEORM_SSL = 'TYPEORM_SSL',
  JWT_SECRET = 'JWT_SECRET',
}
